apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-estudo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/wyller-opus/estudo-argocd.git'
    targetRevision: HEAD
    path: k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
