apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-estudo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: argocd-estudo
  template:
    metadata:
      labels:
        app: argocd-estudo
    spec:
      containers:
      - name: web
        image: nginx:latest
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: html-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: html-config
data:
  index.html: |
    <html><body><h1>Deus e BAO!! d+</h1></body></html>
